### ISSUE TITLE
Appi - Application Creation Using an API First Approach

### ISSUE THREAD

**Issue by BSalita** [kinlane/swagger#3]
Appi is an application development tool that instantly creates cross-platform applications using an API first approach. Appi will benefit the development process by instantly creating code and UI thus greatly reducing development time and costs and facilitating API onboarding. Appi's tool consumes API meta definitions and emits entire applications; program code, UI definitions, and IDE project files.

The project's status is currently in the research and prototyping phase. The current prototype uses Swagger to obtain API metadata and emits a Xamarin (http://www.xamarin.com) application. The Xamarin application consists of cross-platform mobile C# code, Xamarin Forms UI, Visual Studio solution and project files. The generated application will run on Android, iOS and Windows mobile platforms. The code produced by Appi can be used for many purposes such as; a standalone application, scaffolding suitable for creation of more complex applications, for API development, for testing of APIs, for generation of developer API examples.

Appi's approach to application development contrasts with current methods. Typically, today's development process is driven by a marriage of presentation needs, business methods, and available data. An API first approach uses APIs, expressed by metadata, to drive API application development.

Currently, Appi tool's development efforts are following two distinct paths. The first approach is a Visual Studio new project wizard. The wizard is invoked when the developer wishes to create a new application. The wizard prompts for the URL of a Swagger API definition, and the application's target platforms (Android, iOS, ...). The wizard then generates the application. The second approach consists of a standalone application which opens with a list of API choices (e.g. Twitter, Uber). The user selects an API, such as Uber. The application then reads the Uber Swagger definition causing the app to dynamically reconfigure itself as an Uber application.

The quality of an Appi generated application depends on API metadata. Current Swagger 2.0 schema is sufficient for generation of interesting demonstrations such as Uber. We believe that the benefits of an API first approach are so great and varied that it will become a significant method of development. We expect that our project will make key contributions to future API metadata standards.

**Comment by markdstafford** [comment]
Hijacking this issue to have a related converstion. I don't think Kin will mind *too* much. :) Have you seen http://github.com/odata/model-first? It sounds like we are thinking along the same general lines but we were struggling with the amount of effort required to build Swagger docs. So it sounds like we're trying to simplify the API design half of the process and you're improving the scaffolding half of the process. Would love to have a conversation about aligning if you're interested. My direct e-mail is mastaffo@microsoft.com and I'll be at Gluecon if you're there.

**Comment by BSalita** [comment]
I foresee that Appi research will lead towards the need for API patterns and functions. OData

**Comment by BSalita** [comment]
Pretty much nails it - "So it sounds like we're trying to simplify the API design half of the process and you're improving the scaffolding half of the process." Perhaps the mission statement should state "In metadata design, you can never be too easy, too quick to onboard, or too rich in information." I won't be Gluecon so I'll email about Skype-ing.
